### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by mcl-uk** [rppicomidi/pico-usb-host-msc-demo#1]
Hi - thanks for sharing this project, it's exactly what I need for my application. I followed the instructions (BTW there's an error in the readme: msc-usb-host-msc-demo should be: pico-usb-host-demo, also I had to manually pull in funbiscuit/embedded-cli) exactly but got this error during make, any help would be much appreciated, thanks again:

Scanning dependencies of target pico_usb_host_msc_demo
[ 15%] Building C object CMakeFiles/pico_usb_host_msc_demo.dir/pico-usb-host-msc-demo.c.obj
/home/steve/pico/pico-examples/pico-usb-host-msc-demo/pico-usb-host-msc-demo.c: In function 'tuh_msc_mount_cb':
/home/steve/pico/pico-examples/pico-usb-host-msc-demo/pico-usb-host-msc-demo.c:133:51: warning: passing argument 4 of 'tuh_msc_inquiry' from incompatible pointer type [-Wincompatible-pointer-types]
  133 |     tuh_msc_inquiry(dev_addr, lun, &inquiry_resp, inquiry_complete_cb);
      |                                                   ^~~~~~~~~~~~~~~~~~~
      |                                                   |
      |                                                   _Bool (*)(uint8_t,  const msc_cbw_t *, const msc_csw_t *) {aka _Bool (*)(unsigned char,  const msc_cbw_t *, const msc_csw_t *)}
In file included from /home/steve/pico/pico-sdk/lib/tinyusb/src/tusb.h:52,
                 from /home/steve/pico/pico-sdk/lib/tinyusb/hw/bsp/board.h:42,
                 from /home/steve/pico/pico-examples/pico-usb-host-msc-demo/pico-usb-host-msc-demo.c:34:
/home/steve/pico/pico-sdk/lib/tinyusb/src/class/msc/msc_host.h:80:106: note: expected 'tuh_msc_complete_cb_t' {aka '_Bool (*)(unsigned char,  const tuh_msc_complete_data_t *)'} but argument is of type '_Bool (*)(uint8_t,  const msc_cbw_t *, const msc_csw_t *)' {aka '_Bool (*)(unsigned char,  const msc_cbw_t *, const msc_csw_t *)'}
   80 | bool tuh_msc_inquiry(uint8_t dev_addr, uint8_t lun, scsi_inquiry_resp_t* response, tuh_msc_complete_cb_t complete_cb, uintptr_t arg);
      |                                                                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/home/steve/pico/pico-examples/pico-usb-host-msc-demo/pico-usb-host-msc-demo.c:133:5: error: too few arguments to function 'tuh_msc_inquiry'
  133 |     tuh_msc_inquiry(dev_addr, lun, &inquiry_resp, inquiry_complete_cb);
      |     ^~~~~~~~~~~~~~~
In file included from /home/steve/pico/pico-sdk/lib/tinyusb/src/tusb.h:52,
                 from /home/steve/pico/pico-sdk/lib/tinyusb/hw/bsp/board.h:42,
                 from /home/steve/pico/pico-examples/pico-usb-host-msc-demo/pico-usb-host-msc-demo.c:34:
/home/steve/pico/pico-sdk/lib/tinyusb/src/class/msc/msc_host.h:80:6: note: declared here
   80 | bool tuh_msc_inquiry(uint8_t dev_addr, uint8_t lun, scsi_inquiry_resp_t* response, tuh_msc_complete_cb_t complete_cb, uintptr_t arg);
      |      ^~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/pico_usb_host_msc_demo.dir/build.make:76: CMakeFiles/pico_usb_host_msc_demo.dir/pico-usb-host-msc-demo.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1545: CMakeFiles/pico_usb_host_msc_demo.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by rppicomidi** [comment]
@mcl-uk Thank you for reporting this issue. Sorry for the delay in responding. I have been busy. First, I have fixed the typo in the documentation and added a `cd pico-usb-host-msc-demo` step I omitted that may explain why you had to manually pull in the missing submodule libraries.

Second, the build error seems to be that tinyusb API has changed since I wrote this demo. Also, depending on what else has changed, the patch also may no longer be necessary. I will investigate further, hopefully tomorrow. However, if you have already solved it, I would appreciate a pull request.

**Comment by mcl-uk** [comment]
Thanks for responding so quickly. Afraid I haven't already solved it as I'm
rather out of my depth with this stuff! So any help you can offer would be
very much appreciated.
Trouble is I'm now on holiday until the 21st so won't be able to get back
on it until then.
Once again thanks so much for your project and your help.
Cheers, Steve.

**Comment by rppicomidi** [comment]
@mcl-uk Steve when you return from holiday, please get my latest code and have another go. If it solved your problem, please let me know and close the issue. Thanks

**Comment by mcl-uk** [comment]
Thanks a lot. Very much appreciated.
Steve.

**Comment by websterelec** [comment]
Hello - I've installed this successfully so I think your changes are good.  Unrelated to this issue, the data I receive from a cat command on a file that contains nulls doesn't seem correct.  Also, I'm unsure how to use your commands to create and write to a file.  Is that possible?  Thanks for sharing your work!

edit: I think I understand the issue with nulls.  The on_cat command uses f_gets.  I'll have to add a new command that uses f_read.

**Comment by rppicomidi** [comment]
@websterelec Thank you for testing my changes. If you add a new command or make changes to existing command that improves performance, please consider sharing it as a pull request. Currently there is no command for creating and writing to a file unless you are copying from another file (see the `on_cp()` function)

**Comment by mcl-uk** [comment]
YES, thanks again, I can now compile (with pico_w warnings) and run your
  code. However when I type help at the CLI I just get:

---
Pico USB Host Mass Storage Class Demo
date=03/21/2023 time=16:02:42
Please use the CLI to set the date and time for file
timestamps before accessing the filesystem
Type help for more information
 >
Mass Storage drive 0 is mounted
Run the set-date and set-time commands so file timestamps are correct

          USB Flash Disk   rev 0208
Disk Size: 481 MB
Block Count = 985088, Block Size: 512
 > help
  * help
         Print list of commands
 > help
  * help
         Print list of commands
 >
---

  Am I missing something?

**Comment by mcl-uk** [comment]
This is what I now see when building...
![Screenshot from 2023-03-23 11-30-49](https://user-images.githubusercontent.com/44552903/227191840-f736507e-3547-43ab-8cdb-ddb3f558b062.png)

**Comment by rppicomidi** [comment]
@mcl-uk Steve. That's all of the commands. I can reproduce the issue here for command line build, but not in my Visual Studio Code build. It seems something is defining NDEBUG for the command line build, which is making the assert macro fill in no code at all. I will get to the bottom of this and post a solution.

**Comment by rppicomidi** [comment]
@mcl-uk There are two solutions to this. One is to do the build with
```
cmake -DCMAKE_BUILD_TYPE=Debug ..
make
```
The other is to explicitly `#undef NDEBUG` in msc-cli-demo.cpp. I am choosing the latter. New code will be up shortly. Thank you very much for your patience with this and for reporting issues.

I always do my builds in VS Code that by default does a debug build. I am going to go through all of my projects that use the embedded CLI and assert and fix it. Would not have known there was even a problem were it no for your efforts. Thank you again.

**Comment by mcl-uk** [comment]
Yes! I can confirm that undefining NDEBUG fixes the issue (I am using command-line tools). I'll close the issue, but thanks so much for your help and support on this, and thanks once more for sharing your code. I wonder if you'd be interested in collaborating on a pro bono project I'm working on for hackthepoacher.com if so pls get in touch: steve at marvellconsultants dot com.
