### ISSUE TITLE
runtime errors with PIO-usb branch

### ISSUE THREAD

**Issue by mcl-uk** [rppicomidi/pico-usb-host-msc-demo#3]
Thanks for posting your PIO-usb branch code, I've just pulled it and built it (with the usual pico_w warnings), it appeared to run ok until I plugged in the usb stick:
---
Pico USB Host Mass Storage Class Demo
date=04/05/2023 time=10:05:23
Please use the CLI to set the date and time for file
timestamps before accessing the filesystem
Type help for more information
> F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
F2 not ready
[CYW43] do_ioctl(2, 263, 16): timeout
[CYW43] STALL(0;46-46): timeout
[CYW43] do_ioctl(2, 263, 16): timeout
[CYW43] STALL(0;46-46): timeout
[CYW43] do_ioctl(2, 263, 16): timeout
---
And if I power-up with a memory stick already in place I get this:
---
Pico USB Host Mass Storage Class Demo
date=04/05/2023 time=10:05:23
Please use the CLI to set the date and time for file
timestamps before accessing the filesystem
Type help for more information
> [CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
---
Any ideas?
Thanks again for your time.

**Comment by rppicomidi** [comment]
@mcl-uk Steve, that will happen if you compile for the Pico W board but run on a regular Pico board. Make sure you do not set the environment variable `PICO_BOARD` to `pico_w` if you are running on a regular Pico board. If you are seeing this issue with a Pico W board, then I suspect something is wrong with your Pico W board or there is a new bug that I am not aware of.

**Comment by mcl-uk** [comment]
@rppicomidi, I am running on a pico_w. Your native usb demo code runs fine on it, is it worth testing WiFi functionality to double check the CYW43?
I should also mention that the LED blinks as expected until a USB stick is plugged in.

**Comment by rppicomidi** [comment]
@mcl-uk It is indeed code bugs.

**Comment by rppicomidi** [comment]
@mcl-uk Bad news. It seems that the Pico W communicates with the radio chip using the PIO hardware. The PIO USB uses all of PIO 1 and most of PIO 0. At a high level, the radio chip driver and the PIO USB appear to be in resource conflict, so neither work. If you need wireless and you need USB for a Pico W project, I believe you need to use the native USB port. I am going to be pushing new code that warns you can't use Pico W with the PIO USB host option.

**Comment by mcl-uk** [comment]
@rppicomidi Thanks for discovering that - kinda makes sense. FYI I re-compiled for the plain pico but ran on a pico_w and apart from the LED not working the CLI worked fine. However the 64KB/s speed limit is still in force - so no advantage in using the PIO variant for me. Once again, thanks for all your support and glad I could help in some small way with your excellent project.

**Comment by rppicomidi** [comment]
@mcl-uk I found the bugs in the Pico-PIO-USB project and fixed the issue. Please get the latest version of the project and checkout the `main` branch if you care to continue to investigate the alternative USB host hardware.

**Comment by mcl-uk** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=pico_w -DRPPICOMIDI_PIO_HOST=1 ..
 : : : : 
CMake Warning:
  Manually-specified variables were not used by the project:
    RPPICOMIDI_PIO_HOST

**Comment by rppicomidi** [comment]
@mcl-uk RPPICOMIDI_PIO_HOST is an environment variable, not a CMake variable. I can make it either if you want.

**Comment by rppicomidi** [comment]
@mcl-uk I just pushed a new version that allows RPPICOMIDI_PIO_HOST to be either a CMake variable or an environment variable.

**Comment by mcl-uk** [comment]
Can't get the CLI to work with this version (on a pico_w) ! I get:
"Pico USB Host Mass Storage Class Demo"
Then on plugging in the USB stick:
---
mount drive /: failed
         USB Flash Disk   rev 0208
Disk Size: 481 MB
Block Count = 985088, Block Size: 512
---
And on un-plugging:
"Mass Storage drive 4 is unmounted"
But at no point do I see the ">" promt or get any response from typed commands.
I have my FTDI cable attached to pins 21..23 = GND, RxD, TxD
???

**Comment by rppicomidi** [comment]
Yeah, this was another release vs. debug thing. During boot, first core 1 launches, then core 0. There is a flag core1_booting so core 0 waits to for core 1 to completely allocate all of its PIO state machines before allocating its own PIO state machine for the CYW43. That flag was not declared volatile, so the release mode was optimizing it away. For good measure, I made core 1 wait for core 0 to fully boot too so that the FAT file system and CLI was initialized before core 1 starting its USB host operation. I think this is fixed now.

Sorry you are the victim of my failure to exhaustively test all build modes and thank you for not giving up on this project. When you are done with it, it might actually be useful.

**Comment by rppicomidi** [comment]
@mcl-uk If you find any other issues, or if this last fix today does not work for you, please file a new issue. I am closing this one because this bug report already contains too many issues. Thanks again for your help testing this project.

**Comment by mcl-uk** [comment]
Sorry, but my original "[CYW43] do_ioctl(2, 263, 16): timeout / [CYW43] STALL(0;31-31): timeout" problems have re-surfaced.

**Comment by rppicomidi** [comment]
@mcl-uk Please describe what you are doing in detail and I will attempt to duplicate. Much to my embarrassment, you have been a reliable finder of issues and I truly appreciate the help.

For what it is worth, I just did a clean release build on my local system and ran it on my hardware. It works fine. This is how I do my testing using a picoprobe and VS Code on running on Ubuntu Linux 22.04LTS.

Wire the picoprobe debug pins and serial port pins to the Pico W board
Plug in a flash drive to the USB A breakout board wired to the Pico W board
Apply power to the USB C breakout wired to the Pico W VBus and ground pins
Plug the picoprobe to the Linux PC
Open a terminal window
```
export PICO_SDK_PATH=$HOME/projects/pico/pico-sdk/
export PICO_BOARD=pico_w
export RPPICOMIDI_PIO_HOST=1
# start openocd in its own terminal
gnome-terminal -- openocd -f interface/picoprobe.cfg -f target/rp2040.cfg
# start minicom in its own terminal
gnome-terminal -- minicom -D /dev/ttyACM0 -b 115200
# launch VisualStudio Code
code
```
In VisualStudio Code
Set the build variant to Release.
Clean and reconfigure all projects.
Rebuild.
Start Debugging
Press the Run button
Go to the terminal window that is running minicom and observe
```
Pico USB Host Mass Storage Class Demo
date=04/10/2023 time=07:15:42
Please use the CLI to set the date and time for file                            
timestamps before accessing the filesystem                                      
Type help for more information                                                  
>                                                                               
Mass Storage drive 0 is mounted                                                 
Run the set-date and set-time commands so file timestamps are correct           
                                                                                
hp       x900w            rev PMAP                                              
Disk Size: 29604 MB                                                             
Block Count = 60628992, Block Size: 512                                         
                                                                                
> 
```

**Comment by mcl-uk** [comment]
I use command line-only tools (couldn't get on with VSCode), also on Ubuntu/x86 here's my shell script to clone,build and run (using a pico probe)
```
# from home/steve/pico ...
rm -r -f pico-usb-host-msc-demo || exit 1
git clone https://github.com/rppicomidi/pico-usb-host-msc-demo.git
cd pico-usb-host-msc-demo || exit 1
git submodule update --recursive --init
mkdir build || exit 1
cd build || exit 1
export PICO_SDK_PATH=/home/steve/pico/pico-sdk
export PICO_BOARD=pico_w
export RPPICOMIDI_PIO_HOST=1
cmake -DCMAKE_BUILD_TYPE=Release -DPICO_BOARD=pico_w -DRPPICOMIDI_PIO_HOST=1 ..
make || exit 1
sudo openocd -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000"  -c "program pico_usb_host_msc_demo.elf verify reset exit"
cd ..
cd ..

```
Here's what I get on the console with a usb-stick plugged in from start.
```
Pico USB Host Mass Storage Class Demo
date=04/10/2023 time=15:51:08
Please use the CLI to set the date and time for file
timestamps before accessing the filesystem
Type help for more information
>
Mass Storage drive 0 is mounted
Run the set-date and set-time commands so file timestamps are correct

         USB Flash Disk   rev 0208
Disk Size: 481 MB
Block Count = 985088, Block Size: 512
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43
[CYW43] Failed to start CYW43

```
If I start up without a USB stick the LED flashes ok until I plug one in,  then I get the do_ioctl timeout messages. I have a feeling this is all to do with the blinking LED - maybe if that LED code wasn't included it would all work???
  
![20230410_155718](https://user-images.githubusercontent.com/44552903/230928154-3618bd80-45e2-4b35-a1a7-57fbaf6298b1.jpg)

**Comment by rppicomidi** [comment]
@mcl-uk I am trying your process now. Also, what versions (git hash) of tinyusb and Pico-PIO-USB are you using? For me:
tinyusb: f7aa716a61db0b951c8632939f1b5d5625d2c191
Pico-PIO-USB: 8e88736f1d95a3fdced264f145f01fd4c33adbee

**Comment by rppicomidi** [comment]
@mcl-uk I just repeated your build steps locally. Differences are the location of my pico-sdk and the picoprobe configuration file I use. But all worked as with my VS Code build.
Also, my pico-sdk git has is:
7f7232541ae4d8bc6ced7a4cac03517719e0880d
And I am using a USB stick and not an SD Card adapter, but that should not create the issue you are seeing.
I presume you are using a Pico W because you eventually need wireless. If that is the case, I need to help you get past the error you are seeing with the LED blink because otherwise you will see it again when you attempt to add wireless support to your final project.

**Comment by mcl-uk** [comment]
I had an out-of-date clone of Pico-PIO-USB (which according to your hash so do you!), it now works as expected _until_ I try a file copy and then everything goes horribly wrong, 
```
> rm test
test deleted
> cp PICT0042.JPG test

usage: cp from-file to-file
> ls
> ls
Error 1 listing files on drive
>
> ls
Error 1 listing files on drive
>
```
I'm now going to give up with the Pico and switch to a Teensy4.1 - more expensive but usb actually works on that platform and at a speed of 8Mb/s - not 64kB/s. RPF need to sort out their USB host support - they should not just rely on TinyUSB to do their work for them. But thanks so much to you for your help and support, I wish you well.

**Comment by rppicomidi** [comment]
@mcl-uk I have not been able to duplicate the issue you are seeing with file copy and delete, but you have already been more than generous with your time. Sorry it did not work out for you and thank you so much for your help finding issues with my code. I hope the Teensy4.1 and the software stack available for it gives you a better experience.
